api:
  key: 3898bdde1ad087adc16a164f00d6fc7b
server:
  port: 8082
  ssl:
    client-auth: need
    enabled: false
    key-alias: movie-info-service
    key-store: classpath:movie-info-service.jks
    key-store-password: trustme
    key-store-provider: SUN
    key-store-type: JKS
    trust-store: classpath:movie-info-service.jks
    trust-store-password: trustme
    trust-store-type: JKS
spring:
  application:
    name: movie-info-service

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true   